### ISSUE TITLE
Random KeyError

### ISSUE THREAD

**Issue by mjs2600** [mjs2600/mimicry#13]
Occasionally this happens: https://travis-ci.org/mjs2600/mimicry/builds/52506167 We should probably figure out why.

**Comment by jlmcgehee21** [comment]
I think I may have an idea why. I'll look into it tonight.

**Comment by jlmcgehee21** [comment]
in line 75, parent_val could be a float, but the way the output dicts from the bayes net are generated, the keys are all ints.

This could be fixed by using int(parent_val). I'm making the change and pushing it right now.

**Comment by mjs2600** [comment]
@jlmcgehee21 we can close this now right?

**Comment by jlmcgehee21** [comment]
Yup Closed.

**Comment by jlmcgehee21** [comment]
Reopened.  I don't think the cause is what I initially thought.

**Comment by mjs2600** [comment]
:cry:

**Comment by jlmcgehee21** [comment]
This is reproducible 100% of the time with integer domains.

I think the problem is at line 140-141.  I only build lookups in the child dict from values that occur in the parent, but if we have an int range, [small_int, bigger_int], I guess your sample generation method can create a parent value that does not appear in the initial distribution...  Does this make sense?

I may be able to fix it by just generating entries in the child dict for all values in the range [small_int, bigger_int].  Do you think this will work?

**Comment by mjs2600** [comment]
@jlmcgehee21 did you ever merge in your fix?

**Comment by jlmcgehee21** [comment]
I think your fix in the sample generation code was the fix for this.  I
just hacked a bunch of stuff into my branch trying to figure out the source
of the problem.  I can probably just kill that branch now and call it
resolved.

**Comment by mjs2600** [comment]
Sounds good.
